<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../Fuyu.Common/Fuyu.Common.csproj" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.4" />
        <PackageReference Include="Microsoft.AspNetCore.WebSockets" Version="2.3.0" />
        <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="2.3.0" />
    </ItemGroup>

</Project>