<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <PropertyGroup>
        <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
        <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
        <ApplicationIcon>Resources\icon.ico</ApplicationIcon>
        <PublishSingleFile>true</PublishSingleFile>
        <SelfContained>true</SelfContained>
    </PropertyGroup>

    <ItemGroup>
        <Resource Include="Resources/icon.ico" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../Fuyu.Common.Backend/Fuyu.Common.Backend.csproj" />
        <ProjectReference Include="../Fuyu.Backend.Core/Fuyu.Backend.Core.csproj" />
        <ProjectReference Include="..\Fuyu.Backend.EFTMain\Fuyu.Backend.EFTMain.csproj" />
        <ProjectReference Include="../Fuyu.Modding/Fuyu.Modding.csproj" />
        <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
    </ItemGroup>

    <ItemGroup>
      <None Update="appsettings.Development.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="appsettings.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Extensions\" />
    </ItemGroup>

    <Target Name="PostClean" AfterTargets="Clean">
        <RemoveDir Directories="$(BaseOutputPath)" />
    </Target>

</Project>